namespace WinFormsApp1;

internal sealed class FeedManagerDialog : Form
{
    private readonly NewsStore _store; private readonly ListView _list=new();
    public FeedManagerDialog(NewsStore store){_store=store;Text="RSSフィード管理";Width=900;Height=500;StartPosition=FormStartPosition.CenterParent;_list.Dock=DockStyle.Fill;_list.View=View.Details;_list.FullRowSelect=true;_list.Columns.Add("名前",150);_list.Columns.Add("URL",300);_list.Columns.Add("有効",55);_list.Columns.Add("お気に入り",85);_list.Columns.Add("最終取得",145);_list.Columns.Add("結果",250);Controls.Add(_list);var bar=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=42};Controls.Add(bar);Add(bar,"追加",(_,_)=>Edit(null));Add(bar,"編集",(_,_)=>{var f=Selected();if(f!=null)Edit(f);});Add(bar,"有効/無効",(_,_)=>{var f=Selected();if(f!=null){f.Enabled=!f.Enabled;_store.SaveFeed(f);LoadFeeds();}});Add(bar,"お気に入り切替",(_,_)=>{var f=Selected();if(f!=null){f.Favorite=!f.Favorite;_store.SaveFeed(f);LoadFeeds();}});Add(bar,"取得テスト",async(_,_)=>await Test());Add(bar,"削除",(_,_)=>{var f=Selected();if(f!=null&&MessageBox.Show(this,$"「{f.Name}」と関連する記事を削除しますか？","確認",MessageBoxButtons.YesNo)==DialogResult.Yes){_store.DeleteFeed(f.Id);LoadFeeds();}});Add(bar,"閉じる",(_,_)=>{DialogResult=DialogResult.OK;Close();});LoadFeeds();}
    private static void Add(Control c,string t,EventHandler h){var b=new Button{Text=t,AutoSize=true};b.Click+=h;c.Controls.Add(b);}
    private Feed? Selected()=>_list.SelectedItems.Count>0?_list.SelectedItems[0].Tag as Feed:null;
    private void LoadFeeds(){_list.Items.Clear();foreach(var f in _store.GetFeeds()){var i=new ListViewItem(f.Name){Tag=f};i.SubItems.Add(f.Url);i.SubItems.Add(f.Enabled?"はい":"いいえ");i.SubItems.Add(f.Favorite?"はい":"いいえ");i.SubItems.Add(f.LastFetched?.ToLocalTime().ToString("yyyy/MM/dd HH:mm")??"-");i.SubItems.Add(f.LastResult);_list.Items.Add(i);}}
    private void Edit(Feed? f){var name=InputDialog.Ask(this,"フィード名",f?.Name??"");if(name==null)return;var url=InputDialog.Ask(this,"RSS/Atom URL",f?.Url??"https://");if(url==null)return;if(!Uri.TryCreate(url,UriKind.Absolute,out var uri)||uri.Scheme is not("http" or "https")){MessageBox.Show(this,"HTTP/HTTPS URLを入力してください。");return;}f??=new Feed();f.Name=name.Trim();f.Url=url.Trim();if(string.IsNullOrWhiteSpace(f.Name)){MessageBox.Show(this,"フィード名を入力してください。");return;}try{_store.SaveFeed(f);LoadFeeds();}catch(Exception ex){MessageBox.Show(this,$"保存できません: {ex.Message}");}}
    private async Task Test(){var f=Selected();if(f==null)return;var reader=new FeedReader(_store);await reader.RefreshAsync(f,new CancellationTokenSource(TimeSpan.FromSeconds(25)).Token);MessageBox.Show(this,f.LastResult,"取得テスト");LoadFeeds();}
}

internal sealed class CategoryManagerDialog : Form
{
    private readonly NewsStore _store; private readonly ListBox _list=new();
    public CategoryManagerDialog(NewsStore store){_store=store;Text="カテゴリ管理";Width=600;Height=450;StartPosition=FormStartPosition.CenterParent;_list.Dock=DockStyle.Fill;Controls.Add(_list);var bar=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=42};Controls.Add(bar);Add(bar,"追加",(_,_)=>AddCategory());Add(bar,"名前/階層変更",(_,_)=>EditCategory());Add(bar,"削除",(_,_)=>{if(_list.SelectedItem is Category c){_store.DeleteCategory(c.Id);LoadCategories();}});Add(bar,"閉じる",(_,_)=>Close());LoadCategories();}
    private static void Add(Control p,string t,EventHandler e){var b=new Button{Text=t,AutoSize=true};b.Click+=e;p.Controls.Add(b);}
    private void LoadCategories(){_list.Items.Clear();foreach(var c in _store.GetCategories())_list.Items.Add(c);}
    private void AddCategory(){using var d=new CategoryEditDialog(_store.GetCategories());if(d.ShowDialog(this)==DialogResult.OK&&d.NameValue is string n){try{_store.SaveCategory(new Category{Name=n,ParentId=(d.ParentCategory.SelectedItem as Category)?.Id});LoadCategories();}catch(Exception ex){MessageBox.Show(this,ex.Message,"カテゴリを保存できません");}}}
    private void EditCategory(){if(_list.SelectedItem is not Category c)return;var all=_store.GetCategories().Where(x=>x.Id!=c.Id&&!x.FullPath.StartsWith(c.FullPath+" > ",StringComparison.Ordinal)).ToList();using var d=new CategoryEditDialog(all,c);if(d.ShowDialog(this)==DialogResult.OK&&d.NameValue is string n){try{_store.UpdateCategory(new Category{Id=c.Id,Name=n,ParentId=(d.ParentCategory.SelectedItem as Category)?.Id});LoadCategories();}catch(Exception ex){MessageBox.Show(this,ex.Message,"カテゴリを変更できません");}}}
}

internal sealed class CategoryEditDialog : Form
{
    public string? NameValue=>_name.Text;public ComboBox ParentCategory=>_parent;private readonly TextBox _name=new();private readonly ComboBox _parent=new();
    internal bool TryValidateName(out string error){if(string.IsNullOrWhiteSpace(_name.Text)){error="分類名が空白です。名前を入力してください。";return false;}if(_name.Text.Trim().Length>80){error="カテゴリ名は80文字以内で入力してください。";return false;}error="";return true;}
    public CategoryEditDialog(List<Category> cats,Category? existing=null){Text=existing==null?"カテゴリ追加":"カテゴリ変更";Width=450;Height=170;StartPosition=FormStartPosition.CenterParent;_name.Text=existing?.Name??"";var p=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(10),ColumnCount=2,RowCount=3};p.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,100));p.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Controls.Add(p);p.Controls.Add(new Label{Text="名前",AutoSize=true},0,0);_name.Dock=DockStyle.Fill;p.Controls.Add(_name,1,0);p.Controls.Add(new Label{Text="親カテゴリ",AutoSize=true},0,1);_parent.Dock=DockStyle.Fill;_parent.DropDownStyle=ComboBoxStyle.DropDownList;_parent.Items.Add("(なし)");foreach(var c in cats)_parent.Items.Add(c);var selected=existing?.ParentId.HasValue==true?cats.FindIndex(x=>x.Id==existing.ParentId.Value)+1:0;_parent.SelectedIndex=selected;p.Controls.Add(_parent,1,1);var b=new Button{Text=existing==null?"追加":"保存"};b.Click+=(_,_)=>{if(!TryValidateName(out var error)){MessageBox.Show(this,error,"入力エラー");_name.Focus();return;}DialogResult=DialogResult.OK;Close();};p.Controls.Add(b,1,2);AcceptButton=b;}
}

internal sealed class RuleDialog : Form
{
    private readonly NewsStore _store;private readonly List<Category> _cats;private readonly ComboBox _cat=new();private readonly TextBox _pattern=new();private readonly ComboBox _field=new();private readonly ComboBox _op=new();private readonly CheckBox _regex=new();private readonly NumericUpDown _priority=new();private readonly ListBox _rules=new();private long _editingId;
    public RuleDialog(NewsStore store,List<Category> cats){_store=store;_cats=cats;Text="分類ルール";Width=720;Height=500;StartPosition=FormStartPosition.CenterParent;var grid=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=8,Padding=new Padding(10)};grid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,130));grid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Controls.Add(grid);_cat.Dock=DockStyle.Fill;_cat.DropDownStyle=ComboBoxStyle.DropDownList;_cat.Items.AddRange(cats.Cast<object>().ToArray());_cat.SelectedIndex=0;_field.DropDownStyle=ComboBoxStyle.DropDownList;_field.Items.AddRange(["タイトル","本文","タイトル＋本文"]);_field.SelectedIndex=2;_op.DropDownStyle=ComboBoxStyle.DropDownList;_op.Items.AddRange(["OR","AND","NOT（いずれも含まない）"]);_op.SelectedIndex=0;_priority.Maximum=1000;_regex.Text="正規表現";AddRow(grid,0,"カテゴリ",_cat);AddRow(grid,1,"キーワード",_pattern);AddRow(grid,2,"対象",_field);AddRow(grid,3,"キーワード結合",_op);AddRow(grid,4,"優先順位",_priority);AddRow(grid,5,"",_regex);var actions=new FlowLayoutPanel{Dock=DockStyle.Fill};var b=new Button{Text="追加/保存",AutoSize=true};b.Click+=(_,_)=>Save();actions.Controls.Add(b);var edit=new Button{Text="選択ルールを編集",AutoSize=true};edit.Click+=(_,_)=>EditSelected();actions.Controls.Add(edit);var delete=new Button{Text="選択ルールを削除",AutoSize=true};delete.Click+=(_,_)=>DeleteSelected();actions.Controls.Add(delete);grid.Controls.Add(actions,1,6);grid.RowStyles.Add(new RowStyle(SizeType.Absolute,40));_rules.Dock=DockStyle.Fill;grid.Controls.Add(_rules,1,7);grid.RowStyles.Add(new RowStyle(SizeType.Percent,100));LoadRules();}
    private static void AddRow(TableLayoutPanel p,int r,string label,Control c){p.RowStyles.Add(new RowStyle(SizeType.Absolute,32));p.Controls.Add(new Label{Text=label,AutoSize=true,TextAlign=ContentAlignment.MiddleLeft},0,r);c.Dock=DockStyle.Fill;p.Controls.Add(c,1,r);}
    private void LoadRules(){_rules.Items.Clear();var names=_cats.ToDictionary(x=>x.Id,x=>x.FullPath);foreach(var r in _store.GetRules())_rules.Items.Add($"{(names.ContainsKey(r.CategoryId)?names[r.CategoryId]:"?")} : {r.Pattern} [{r.Field}, {r.Operator}]");}
    private void EditSelected(){if(_rules.SelectedIndex<0)return;var rule=_store.GetRules()[_rules.SelectedIndex];_editingId=rule.Id;_cat.SelectedItem=_cats.FirstOrDefault(x=>x.Id==rule.CategoryId);_pattern.Text=rule.Pattern;_field.SelectedItem=rule.Field;_op.SelectedItem=rule.Operator;_regex.Checked=rule.IsRegex;_priority.Value=Math.Min(Math.Max(rule.Priority,0),(int)_priority.Maximum);}
    private void DeleteSelected(){if(_rules.SelectedIndex<0)return;var rule=_store.GetRules()[_rules.SelectedIndex];_store.DeleteRule(rule.Id);if(rule.Id==_editingId)_editingId=0;LoadRules();}
    private void Save(){var p=_pattern.Text.Trim();if(p.Length==0||_cat.SelectedItem is not Category cat)return;if(_regex.Checked)try{foreach(var term in p.Split(new[]{';',',','\n','\r'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).Where(x=>x.Length>0))_ = new System.Text.RegularExpressions.Regex(term);}catch(Exception ex){MessageBox.Show(this,ex.Message,"正規表現エラー");return;}_store.SaveRule(new ClassificationRule{Id=_editingId,CategoryId=cat.Id,Pattern=p,Field=_field.Text,Operator=_op.Text,IsRegex=_regex.Checked,Priority=(int)_priority.Value});_editingId=0;_pattern.Clear();LoadRules();}
}

internal sealed class InterestDialog : Form
{
    private readonly NewsStore _store;private readonly ComboBox _cat=new();private readonly TextBox _term=new();private readonly ListBox _list=new();private readonly List<Category> _cats;
    public InterestDialog(NewsStore store,List<Category> cats){_store=store;_cats=cats;Text="興味・関心";Width=520;Height=400;StartPosition=FormStartPosition.CenterParent;var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=72};_term.Width=180;_cat.Width=170;_cat.DropDownStyle=ComboBoxStyle.DropDownList;_cat.Items.Add("キーワードのみ");_cat.Items.AddRange(cats.Cast<object>().ToArray());_cat.SelectedIndex=0;top.Controls.Add(new Label{Text="キーワード",AutoSize=true,Padding=new Padding(2,8,0,0)});top.Controls.Add(_term);top.Controls.Add(_cat);var b=new Button{Text="追加"};b.Click+=(_,_)=>Save();top.Controls.Add(b);Controls.Add(_list);Controls.Add(top);_list.Dock=DockStyle.Fill;LoadItems();}
    private void LoadItems(){_list.Items.Clear();var names=_cats.ToDictionary(x=>x.Id,x=>x.FullPath);foreach(var i in _store.GetInterests())_list.Items.Add(i.CategoryId.HasValue?(names.ContainsKey(i.CategoryId.Value)?names[i.CategoryId.Value]:"?")+" / "+i.Term:i.Term);}
    private void Save(){var t=_term.Text.Trim();if(t.Length==0)return;_store.SaveInterest(t,(_cat.SelectedItem as Category)?.Id);_term.Clear();LoadItems();}
}

internal static class InputDialog
{
    public static string? Ask(IWin32Window owner,string title,string initial){using var form=new Form{Text=title,Width=550,Height=145,StartPosition=FormStartPosition.CenterParent};var text=new TextBox{Left=12,Top=12,Width=505,Text=initial};var ok=new Button{Text="OK",DialogResult=DialogResult.OK,Left=352,Top=48,Width=78};var cancel=new Button{Text="キャンセル",DialogResult=DialogResult.Cancel,Left=439,Top=48,Width=78};form.Controls.AddRange([text,ok,cancel]);form.AcceptButton=ok;form.CancelButton=cancel;return form.ShowDialog(owner)==DialogResult.OK?text.Text:null;}
}
